### ISSUE TITLE
Param start_date not effective

### ISSUE THREAD

**Issue by instantkaffee** [bgreenawald/projmanr#4]
```
library(projmanr)
(df <- taskdata1)
res <- critical_path(df)
data <- taskdata1
gantt(data, start_date = "2018-01-01")
```

Seems current version does not make use the param.

**Comment by bgreenawald** [comment]
Thank you for pointing this out! This was discovered a while back and should be fixed on the version currently on Github (installation instruction are on the README if you want to try it out) and will be patched in the next version. I'm closing the issue for now but please re-open it if the problem persists.
